server:
  port: 1000
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://localhost:1000/eureka/


